server:
  port: 8081

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    hikari:
      username: username
      password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: username
      password: password
  docker:
    compose:
      skip:
        in-tests: false