### POST new product
POST http://localhost:8081/api/products
Authorization: Basic username password
Content-Type: application/json

{
  "name": "p-1",
  "description": "product number 1",
  "price": 5.46,
  "categoryId": 1
}

### GET all products
GET http://localhost:8081/api/products
Accept: application/json
Authorization: Basic username password

### GET sum of products prices
GET http://localhost:8081/api/products/price/total
Accept: application/json
Authorization: Basic username password

### GET product by id
GET http://localhost:8081/api/products/1
Accept: application/json
Authorization: Basic username password

### PUT new product by id
PUT http://localhost:8081/api/products/1
Authorization: Basic username password
Content-Type: application/json

{
  "name": "p-2",
  "description": "product number 2",
  "price": 1.44,
  "categoryId": 1
}

### DELETE product by id
DELETE http://localhost:8081/api/products/1
Authorization: Basic username password
